import { PARTICIPANT_PERMISSION_OPTIONS } from "./type";

export const PARTICIPANT_PERMISSION_LABELS = {
  [PARTICIPANT_PERMISSION_OPTIONS.VIEW]: "閲覧",
  [PARTICIPANT_PERMISSION_OPTIONS.REQUEST]: "依頼",
  [PARTICIPANT_PERMISSION_OPTIONS.INPUT]: "入力",
  [PARTICIPANT_PERMISSION_OPTIONS.EDIT]: "編集",
};
